version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: doctrine/dbal
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: laravel/framework
    versions:
    - 6.20.12
    - 6.20.14
    - 6.20.17
    - 6.20.18
    - 6.20.19
    - 6.20.20
    - 6.20.22
    - 6.20.23
  - dependency-name: barryvdh/laravel-debugbar
    versions:
    - 3.5.5
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.69
    - 0.12.70
    - 0.12.73
    - 0.12.76
    - 0.12.78
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.83
  - dependency-name: filp/whoops
    versions:
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
    - 1.4.3
  - dependency-name: thinktomorrow/assetlibrary
    versions:
    - 0.7.5
    - 0.7.7
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
  - dependency-name: webmozart/assert
    versions:
    - 1.10.0
  - dependency-name: spatie/laravel-activitylog
    versions:
    - 3.17.0
  - dependency-name: spatie/laravel-permission
    versions:
    - 4.0.0
  - dependency-name: nunomaduro/collision
    versions:
    - 3.2.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
    - 1.1.4
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: browser-sync
    versions:
    - 2.26.14
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: sortablejs
    versions:
    - 1.13.0
  - dependency-name: browser-sync-webpack-plugin
    versions:
    - 2.3.0
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: vue-loader
    versions:
    - 15.9.6
