<div>
    <livewire:chief-wire::file-upload
        :field-id="$field->getId()"
        :field-name="$field->getName($locale)"
        :allow-multiple="$field->allowMultiple()"
        :existing-files="$field->getValue($locale)"
        :components="$field->getComponents()"
    />
</div>
