name: Test

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3, 8.4 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute unit tests
        run: vendor/bin/phpunit --testsuite unit

      - name: Execute application tests
        run: vendor/bin/phpunit --testsuite application

      - name: Execute forms tests
        run: vendor/bin/phpunit --testsuite forms

      - name: Execute assets tests
        run: vendor/bin/phpunit --testsuite assets

      - name: Execute models tests
        run: vendor/bin/phpunit --testsuite models

      - name: Execute fragments tests
        run: vendor/bin/phpunit --testsuite fragments

      - name: Execute menu tests
        run: vendor/bin/phpunit --testsuite menu

      - name: Execute table tests
        run: vendor/bin/phpunit --testsuite table

      - name: Execute urls tests
        run: vendor/bin/phpunit --testsuite urls

      - name: Execute sites tests
        run: vendor/bin/phpunit --testsuite sites
